apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-router
  labels:
    app: fastapi-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-router
  template:
    metadata:
      labels:
        app: fastapi-router
    spec:
      containers:
      - name: fastapi-router
        image: my-fastapi-router:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: DISTILBERT_URL
          value: "http://nlp-distilbert-service:8001/infer"
        - name: BERT_URL
          value: "http://nlp-bert-service:8001/infer"
        - name: ROBERTA_URL
          value: "http://nlp-roberta-service:8001/infer"
        - name: DEBERTA_URL
          value: "http://nlp-deberta-service:8001/infer"
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi-router
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
