apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
data:
  logstash.conf: |
    input {
      http {
        port => 5000
        codec => json
      }
    }
    filter {
      mutate {
        remove_field => ["headers", "host"]
      }
    }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "nlp-inference-%{+YYYY.MM.dd}"
      }
      stdout { codec => rubydebug }
    }
