apiVersion: v1
kind: ServiceAccount

metadata:
  name: telemetry-service-account

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: telemetry-role
  namespace: default

rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - nodes
    verbs:
      - get
      - list
      - watch

  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch

  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: telemetry-rolebinding
  namespace: default

subjects:
  - kind: ServiceAccount
    name: telemetry-service-account
    namespace: default

roleRef:
  kind: Role
  name: telemetry-role
  apiGroup: rbac.authorization.k8s.io